pipeline:
  name: Build go
  identifier: Build_go
  projectIdentifier: training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: why_not
        identifier: why_not
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "we are here!"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: build_it
        identifier: build_it
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Go App
                  identifier: build_go_app
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: false
            paths: []
        delegateSelectors:
          - custom-delegate
  delegateSelectors:
    - docker-delegate
