pipeline:
  identifier: Build_gosample_1697489656531
  name: Build gosample
  orgIdentifier: default
  projectIdentifier: training
  properties:
    ci:
      codebase:
        connectorRef: account.github_go
        build: <+input>
        prCloneStrategy: MergeCommit
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      go build
                      go test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
